import re

SAMPLE_RATE = 16000
CHANNELS = 1
BITS_PER_SAMPLE = 16
BYTES_PER_SAMPLE = BITS_PER_SAMPLE // 8
WAV_CONTENT_TYPE = "audio/wav"
INIT_VOICE_TIMEOUT = 5.0
UNRESOLVED_NAME_RE = re.compile(r"^speaker\b", re.IGNORECASE)
